[Documentation] Content update
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #40
Opened 2020-11-13 13:03 UTC by nelsonsouthworks

## Description
Documentation fixes and improvements have been made.

## Specific Changes

- Change bullet by numbers. 
- Change the order of bullets 
- Improve Deploy documentation 
- Add a note that all resources have to be created in the same location (preferably create them in the **West US location**) 
- Create and setup BlobStorage doc
  - Specify that 2 containers should be created (hr-data-container and prod-conversations) and the names of each one
  - Include the creation step for **hrDataEmployees.json** file

2020-11-13 16:18 UTC, gonzalorieto requested changes
Hey @nelsonsouthworks, I left some comments

2020-11-13 20:21 UTC, nelsonsouthworks commented on docs/Blobstorage&Container.md
> +- After the storage account is created, you need to create **two new containers**. The first container **hr-data-container** which will have a json file where the birthday data will be saved. And fin
Thanks for your suggestion, I think this part could be improved.

2020-11-13 20:28 UTC, dfavretto commented on docs/AzureFunction.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs (it is recommended to use the location **West US**).
I would say it's our internal recommendation, but I wouldn't make that recommendation to people external to us, since they may be in another location that suits better for them

2020-11-13 20:29 UTC, nelsonsouthworks commented on docs/AzureFunction.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs (it is recommended to use the location **West US**).
Good question, in our case it is necessary to be in West US, to have everything in the same location. And in this location, there are the necessary resources for the operation of the BOT and it is among the lowest cost according to the information on this[ page](https://azureprice.net/Region).

2020-11-13 20:32 UTC, nelsonsouthworks commented on docs/AzureFunction.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs (it is recommended to use the location **West US**).
Ok @dfavretto , I'm going to modify and let it only try to create everything within the same location. Thanks

2020-11-18 19:41 UTC, famatas reviewed
I left some comments.

2020-11-18 19:41 UTC, famatas commented on docs/Blobstorage&Container.md
> +To create a new container, we click on add Container. Then enter a name, which in this case would be **hr-data-container** and select at the public access level Private and then click create. We will
We could highlight `Add Container` (or `+ Container` as in the screenshot.)

2020-11-18 19:41 UTC, famatas commented on docs/Blobstorage&Container.md
> +- Finally we need to upload a file to the ** hr-data-container ** container, as follows:
It is rendering bad.
![image](https://user-images.githubusercontent.com/62260992/99578910-3eda0c80-29bc-11eb-84e5-6994b87d8566.png)

2020-11-18 19:41 UTC, famatas commented on docs/RepublishBot.md
> +# Republis Bot
Republish 😅. This change could break some links. Be careful.

2020-11-18 19:41 UTC, famatas commented on docs/resources/hrDataEmployees.json
> +        "Email": "prueba@email.com"
I think we should change `prueba` to `test`.

2020-11-18 20:41 UTC, angelszymczak requested changes

2020-11-18 20:41 UTC, angelszymczak commented on docs/Blobstorage&Container.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs.
Hi @nelsonsouthworks,
What do you think about "save costs" instead of "cut costs"?

2020-11-18 20:46 UTC, nelsonsouthworks commented on docs/AzureFunction.md
> +It is necessary to change the **TimeZone** of our **Azure Function** to be according to our need, for this we will repeat the previous steps of how to create a **new appication setting**, only that w
Thank you for the correction

2020-11-18 20:46 UTC, nelsonsouthworks commented on docs/AzureFunction.md
> +    **Schedule** could be configure as the classic [cronjob espression](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#ncrontab-expressions).
Thank you for the correction

2020-11-18 20:46 UTC, nelsonsouthworks commented on docs/resources/hrDataEmployees.json
> +        "Email": "prueba@email.com"
Thank you for the correction

2020-11-18 20:46 UTC, nelsonsouthworks commented on docs/RepublishBot.md
> +# Republis Bot
Thank you for the correction

2020-11-18 20:47 UTC, nelsonsouthworks commented on docs/Blobstorage&Container.md
> +To create a new container, we click on add Container. Then enter a name, which in this case would be **hr-data-container** and select at the public access level Private and then click create. We will
Very good suggestion. I will apply it. Thanks

2020-11-18 20:49 UTC, nelsonsouthworks commented on docs/Blobstorage&Container.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs.
I like the recommendation you made. I'm going to apply it. Thank you

2020-11-19 13:36 UTC, dfavretto commented on docs/Blobstorage&Container.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs.
I think "to reduce costs" sounds even better, what do you think?

2020-11-19 13:37 UTC, nelsonsouthworks commented on docs/Blobstorage&Container.md
> +> When choosing the **location** for your new resource, remember to use the same region for all new resources to cut costs.
I think your suggestion is great. Thanks

2020-11-19 15:08 UTC, angelszymczak approved these changes

2020-11-19 20:04 UTC, dfavretto requested changes

2020-11-19 20:04 UTC, dfavretto commented on docs/RepublishBot.md
> +[← Back to Table of contents](README.md#table-of-contents)
Why are the deployment instructions for both Visual Studio and CLI, but regarding the Republish there are only instructions for Visual Studio?

2020-11-20 15:18 UTC, dfavretto submitted a review, later dismissed

2020-11-20 15:19 UTC, angelszymczak approved these changes

2020-11-20 18:34 UTC, gonzalorieto approved these changes
LGTM!

2020-11-20 19:03 UTC, merged