Glorieto/proactive function project
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #45
Opened 2020-11-23 18:44 UTC by gonzalorieto

## Description
Added a Proactive Function (Time triggered) to the **Birthday Bot** solution. The function proactively start the birthday greeting flow making an `GET` request to the `api/notify` endpoint of the **Birthday Bot**.

## Specific Changes
Please list the changes in a concise manner.

  - Added whole Azure Function project to solution

2020-11-25 20:05 UTC, angelszymczak commented
Hi @gonzalorieto ,
The name of module/folder "ProactiveFunction" isn't very descriptive.
I would expect to find on the project any folder like "Capabilities" and inside them, some like "Proactivity".

What do you think about it?

2020-11-26 14:19 UTC, famatas reviewed
Maybe we should rename this folder, it has the `Birthday-Bot` as sufffix. Is there any reason for it to start with that name? 
![image](https://user-images.githubusercontent.com/62260992/100361630-26c84580-2fd9-11eb-8c41-f2bb645b9469.png)

2020-12-01 13:56 UTC, angelszymczak commented on Birthday-Bot.ProactiveFunction/Properties/ServiceDependencies/birthday-bot-functions - Zip Deploy/profile.arm.json
> +      "defaultValue": "bot-training-kit",
I think that it should be configurable from any external variable.

2020-12-01 14:01 UTC, famatas commented on Birthday-Bot.ProactiveFunction/Properties/ServiceDependencies/birthday-bot-functions - Zip Deploy/profile.arm.json
> +      "defaultValue": "bot-training-kit",
This file is an ARM template for deployments, and I think it was created by Visual Studio.

2020-12-01 14:06 UTC, angelszymczak requested changes
The ARM template file has **Dev** environment configuration.
I think that to be a configurable stack you could [create](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files) an external `parameter.json` file to fill environments settings to the ARM template file.

2020-12-01 14:11 UTC, angelszymczak commented
It's a good idea to use the present imperative tense on PR naming.
You can learn more [here](https://chris.beams.io/posts/git-commit/#imperative).

2020-12-02 12:23 UTC, gonzalorieto commented on Birthday-Bot.ProactiveFunction/Properties/ServiceDependencies/birthday-bot-functions - Zip Deploy/profile.arm.json
> +      "defaultValue": "bot-training-kit",
File deleted

2020-12-02 14:21 UTC, angelszymczak submitted a review, later dismissed

2020-12-02 14:51 UTC, dfavretto commented on birthday-bot/Birthday-Bot.csproj
> +  </ItemGroup>
Is it possible this change happened at the beginning because you added the other project to this solution, and now this change is obsolete?

2020-12-02 14:53 UTC, dfavretto requested changes

2020-12-02 14:53 UTC, dfavretto commented on birthday-bot/Startup.cs
> +            services.AddSingleton<IBotFrameworkHttpAdapter, AdapterWithErrorHandler>();
Is this change necessary? What does it have to do with the MessagePublisher project?

2020-12-02 14:53 UTC, dfavretto commented on birthday-bot/Events/AzureEventHubProducer.cs
> +        }
Is this change necessary? What does it have to do with the MessagePublisher project?

2020-12-02 14:53 UTC, dfavretto commented on birthday-bot/Controllers/NotifyController.cs
> +            var resposne = await turnContext.SendActivityAsync(happyBirthdayMessage);
Is this change necessary? What does it have to do with the MessagePublisher project?

2020-12-02 15:34 UTC, gonzalorieto commented on birthday-bot/Birthday-Bot.csproj
> +  </ItemGroup>
It could be the case. I removed it.

2020-12-02 15:34 UTC, gonzalorieto commented on birthday-bot/Events/AzureEventHubProducer.cs
> +        }
Removed

2020-12-02 15:34 UTC, gonzalorieto commented on birthday-bot/Startup.cs
> +            services.AddSingleton<IBotFrameworkHttpAdapter, AdapterWithErrorHandler>();
Removed

2020-12-02 15:34 UTC, gonzalorieto commented on birthday-bot/Controllers/NotifyController.cs
> +            var resposne = await turnContext.SendActivityAsync(happyBirthdayMessage);
Removed

2020-12-02 15:58 UTC, dfavretto approved these changes

2020-12-02 15:59 UTC, merged