Azure Queue integration with Birthday Bot
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #46
Opened 2020-11-26 16:01 UTC by nelsonsouthworks

## Description
Necessary changes to let the Birthday-Bot publish messages on the Azure Queue to achieve proactive messaging in the future.

## Specific Changes

  - Create `IQueueProducer`interface and `QueueProducer` implementation.
  - Integrate `QueueProducer` into `NotifyController` to send events along with Slack greetings.
  - Accommodate `OnConversationUpdateActivityAsync` async call

2020-11-27 13:36 UTC, famatas reviewed
I left some comments.

2020-11-27 13:36 UTC, famatas commented on birthday-bot/Controllers/NotifyController.cs
>  using Birthday_Bot.Events;
You are not using `Birthday_bot.Events` anymore. I think you can remove the `using`.
![image](https://user-images.githubusercontent.com/62260992/100454225-4031c600-309b-11eb-86b1-c66fb70aaf59.png)

2020-11-27 13:36 UTC, famatas commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
We used the user `123` as testing, but before merge the branch you should change the user to something more representative, like `Birthday_Bot`

2020-11-27 13:36 UTC, famatas commented on birthday-bot/Startup.cs
>  using Birthday_Bot.Events;
You are not using `Birthday_bot.Events` anymore. I think you can remove the using.
![image](https://user-images.githubusercontent.com/62260992/100454693-32307500-309c-11eb-83ae-96a21f9bca21.png)

2020-11-27 15:19 UTC, dfavretto commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
We aren't using the UserID in the Southworks Assistant, right?

2020-11-27 17:03 UTC, famatas commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
The Southworks Assistant uses the `EventData` object which has the `UserId` property, but this property is not used at this moment and it comes from previous commits. Maybe we could use it if we research how to use the proactive model or when we have more bots or skills to identify where the message comes from.
![image](https://user-images.githubusercontent.com/62260992/100471549-45057280-30b9-11eb-84f8-8c9167edbc63.png)

2020-11-30 12:51 UTC, dfavretto commented on birthday-bot/appsettings.json
> +  "BambooHRUsersFileName": "",
What is this value for? I don't see it referenced anywhere else in this PR

2020-11-30 13:23 UTC, nelsonsouthworks commented on birthday-bot/appsettings.json
> +  "BambooHRUsersFileName": "",
Thanks for your suggestion, the parameter was removed. Since by mistake it was added

2020-11-30 18:17 UTC, dfavretto requested changes

2020-11-30 18:17 UTC, dfavretto commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
Alright, then it doesn't really matter what we save here as UserID, it won't be used. However, I don't like the idea of hardcoding a random number like `123`, at least make it a real ID, like `azbirthdaybot`.

2020-11-30 18:54 UTC, nelsonsouthworks commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
@dfavretto thank you for your suggestion regarding this parameter. You could set it from the appsettings.json in the same way that it is done for the Event Hubs, what do you think?

![image](https://user-images.githubusercontent.com/64040734/100651429-2e168880-3324-11eb-974c-54af328daa82.png)

2020-11-30 19:00 UTC, dfavretto commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
I don't like that idea, I just want to change a random hardcoded number (`123`) to a more relatable hardcoded name (`azbirthdaybot`), we should stop adding more and more things to the appsettings, specially this one that won't be used for the moment.

2020-11-30 19:02 UTC, nelsonsouthworks commented on birthday-bot/Queue/QueueProducer.cs
> +            CustomEventData customQueue = new CustomEventData("123", message);
Great I agree. I will apply your suggestion. Thanks

2020-11-30 19:06 UTC, dfavretto approved these changes

2020-11-30 19:06 UTC, merged