[Documentation] Add new Azure Queue section
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #47
Opened 2020-12-02 15:33 UTC by nelsonsouthworks

## Description
A new Azure Queue section has been added corresponding to the feature implemented in the project.

## Specific Changes

  - Added an **Azure Queue** section.

2020-12-02 18:38 UTC, dfavretto requested changes
I have two concerns. The first one is about the picture `queue-operation-sample.png` as it is showing two different messages, it would be great if they were the same text. Also, the `Features [New]` section added to the Readme, it doesn't feel like a suitable change. Maybe if it is not mandatory for the Bot configuration process as the other steps, we can have it separated, but without the `[New]` tag.

2020-12-02 19:02 UTC, nelsonsouthworks commented
Great @dfavretto , thanks for your suggestions. I'm going to change the image and remove the ``Features [New]``

2020-12-02 19:07 UTC, nelsonsouthworks commented
Correct, it is necessary to add the step of how to set the flag to indicate where you want to send the message. Thanks @dfavretto

2020-12-03 14:11 UTC, gonzalorieto commented on docs/AzureQueue.md
> + (It's 64,000 characters. Since the average word in English is 4.7 characters, that allows up to 13,617 words.)
Interesting data!

2020-12-03 14:24 UTC, famatas reviewed
I left some comments. Also, we should indicate that the use of queues is optional, the ` AzureQueue.md`  file starts with how to configure queues and later how to enable this feature, but if I don't want to use queues I should skip this document.

2020-12-03 14:24 UTC, famatas commented on docs/AzureQueue.md
> +- **QueueName**: you must define the name that would be assigned to the Queue.
Did you get this from any documentation? It looks some weird with the quotes.

![image](https://user-images.githubusercontent.com/62260992/101031545-656d7b00-3558-11eb-9e00-760cc8c690af.png)

 What do you think to use something like this ``http://your-storage-account.queue.core.windows.net/your-queue-name``

2020-12-03 14:24 UTC, famatas commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
It seems like the only feature of the Birthday Bot is the use of Storage Queues. I think that should not be in the readme.

2020-12-03 14:42 UTC, gonzalorieto requested changes
Hey @nelsonsouthworks, left some comments!

2020-12-03 14:42 UTC, gonzalorieto commented on docs/AzureQueue.md
> +- Maximum time that the message is sent is 7 days.
If the intention is say the message will live up to 7 days in the queue, then consider changing the sentence to something like:
- Maximum time a message can remain in a queue is 7 days.

2020-12-03 14:42 UTC, gonzalorieto commented on docs/AzureQueue.md
> +- Possibility so that the message does not expire adding -1.
Add the name of the parameter.

2020-12-03 19:38 UTC, nelsonsouthworks commented on docs/AzureQueue.md
> +- **QueueName**: you must define the name that would be assigned to the Queue.
I like your suggestions, I will apply it. Thanks

2020-12-03 19:38 UTC, nelsonsouthworks commented on docs/AzureQueue.md
> +- Maximum time that the message is sent is 7 days.
I like your suggestions, I will apply it. Thanks

2020-12-03 19:42 UTC, nelsonsouthworks commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
Good point, instead would you think that it is in accordance? I put it in this place, since it is an extra implementation after having configured the Azure Birthday Bot

2020-12-03 19:53 UTC, nelsonsouthworks commented on docs/AzureQueue.md
> +- Possibility so that the message does not expire adding -1.
Great, I'm going to add the name of the parameter. Thanks

2020-12-03 20:21 UTC, gonzalorieto submitted a review, later dismissed
LGTM!

2020-12-03 20:23 UTC, famatas commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
I'm not sure where it can be located, or just changing the title could be better, maybe optional features? what do you think? It is just a comment, maybe the best approach is to leave the `Feature` title.

2020-12-03 20:28 UTC, nelsonsouthworks commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
I liked the ``optional features`` thing, I take it. Thanks

2020-12-04 13:59 UTC, angelszymczak requested changes

2020-12-04 13:59 UTC, angelszymczak commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
The feature is not "Azure Feature", but the ability to configure a proactive asynchronous channel. I think it should be the next step to the creation of the Azure Function and it could be labeled as optional. Or maybe advanced settings?

@dfavretto, what do you think about it?

2020-12-04 14:21 UTC, famatas reviewed
I left a comment. The rest LGTM!. Just a question, this is a public repo, should we start to use 
[gitmoji](https://gitmoji.carloscuesta.me/)? @dfavretto @angelszymczak @gonzalorieto what do you think?

2020-12-04 14:21 UTC, famatas commented on docs/AzureQueue.md
> +- **URL format**: Queues are addressable using the following URL format: ``http://your-storage-account.queue.core.windows.net/your-queue-name``.
This sound weird, the `URL format` is a component of a Queue? If you check [the documentation](https://docs.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet), these elements aren't `components`, they are `Queue Service Concepts`.

![image](https://user-images.githubusercontent.com/62260992/101174086-26a3f780-3622-11eb-8b9f-4ab72e1e503b.png)

2020-12-04 14:46 UTC, nelsonsouthworks commented on docs/AzureQueue.md
> +- **URL format**: Queues are addressable using the following URL format: ``http://your-storage-account.queue.core.windows.net/your-queue-name``.
Great, I'll change the title to ``Queue Service Concepts``. Thanks

2020-12-04 17:39 UTC, angelszymczak approved these changes
LGTM+

2020-12-04 18:38 UTC, dfavretto commented on docs/README.md
> +- [Azure Queue](AzureQueue.md#azure-queue)
> the feature is the option to configure a proactive asynchronous channel

I agree in this with @angelszymczak , the Azure Queue integration allows you to use this new feature of publishing the messages somewhere so any third party can consume them.

2020-12-09 13:35 UTC, famatas submitted a review, later dismissed

2020-12-09 18:46 UTC, angelszymczak requested changes
Hi @nelsonsouthworks,
the PR looks good to me, just I left a little change request.

On the other hand, the branch is not descriptive at all, keep this in mind for the next branch.
It could be named like `nvila/add-azure-queue-doc`.

2020-12-09 18:46 UTC, angelszymczak commented on docs/AzureQueue.md
> +You need to define two new parameters in the appsettings.json file for the connection with Azure Queue:
Hi @nelsonsouthworks,
I think that appsetting.json should be highlighted.

2020-12-09 19:39 UTC, angelszymczak approved these changes

2020-12-10 18:53 UTC, dfavretto commented on docs/AzureQueue.md
> +You need to define two new parameters in the appsettings.json file for the connection with Azure Queue:
@nelsonsouthworks I think @angelszymczak meant the word in the text, not in the title. Also, why the double quote? It should be ok with just one
![image](https://user-images.githubusercontent.com/23645105/101816356-b0aaff00-3aff-11eb-8fea-e110629292cc.png)

2020-12-10 19:17 UTC, dfavretto requested changes
Left a suggestion to change the linked document to clarify the use of Azure Queue. When this and the previous suggestion about highlighting `appsettings.json` are done, I'll approve and merge the PR

2020-12-10 19:17 UTC, dfavretto commented on docs/README.md
> +- [Asynchronous Proactive Messages](AzureQueue.md#azure-queue)
```suggestion
- [Asynchronous Proactive Messages with Azure Queue](AzureQueue.md#azure-queue)
```

2020-12-10 21:06 UTC, dfavretto approved these changes

2020-12-10 21:06 UTC, merged