[Documentation] Improve the deployment step via CLI
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #49
Opened 2020-12-11 13:49 UTC by nelsonsouthworks

Fixes #41  
 
## Description
Improved step 6 of the **DeployAzurePortal.md** file has been, specifying that the value of the `<FOLDER_NAME>` parameter has to be a **relative path**.

## Specific Changes
  - Improved the content of **DeployAzurePortal.md** file.

2020-12-11 17:34 UTC, angelszymczak approved these changes

2020-12-11 17:46 UTC, famatas submitted a review, later dismissed

2020-12-14 17:55 UTC, angelszymczak requested changes

2020-12-14 17:55 UTC, angelszymczak commented on docs/DeployAzurePortal.md
> +    dotnet publish -o <FOLDER-NAME>
Hi @nelsonsouthworks,
What would be the format of the name of this folder?

2020-12-14 18:20 UTC, nelsonsouthworks commented on docs/DeployAzurePortal.md
> +    dotnet publish -o <FOLDER-NAME>
Hi @angelszymczak , `<FOLDER-NAME>` should be replaced by the relative path of the folder that you choose as output. The name of the folder will depend on the one you assign it. Thanks

2020-12-14 18:25 UTC, angelszymczak approved these changes

2020-12-15 15:33 UTC, dfavretto requested changes

2020-12-15 15:33 UTC, dfavretto commented on docs/DeployAzurePortal.md
> +    > **NOTE:** Before executing this command, the `<FOLDER-NAME>` path must exist. Whose path has to be of the **relative type**. The `-o` command option indicates the output directory.
The phrase `Whose path has to be of the **relative type**.` is not quite correct here, as `whose` means `the path that belongs to someone` and in this case you are not taking about anyone. However, I think this comment is unnecessary, as the path can be both relative or absolute, there's no limitation to that, since a relative path is translated to an absolute path at execution time.

2020-12-16 13:27 UTC, gonzalorieto commented on docs/DeployAzurePortal.md
> +    > **NOTE:** Before executing this command, the `<FOLDER-NAME>` path must exist. Whose path has to be of the **relative type**. The `-o` command option indicates the output directory.
Just put `path must be relative`.

2020-12-17 13:23 UTC, angelszymczak approved these changes

2020-12-17 13:43 UTC, dfavretto approved these changes

2020-12-17 13:44 UTC, merged