Change step for json file creation
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #50
Opened 2020-12-11 15:32 UTC by nelsonsouthworks

Fixes #48 

## Description
The method was changed to have a base file to load birthdays in `Blobstorage & Container.md` file.
 
## Specific Changes
  - Change in step 6 for birthday base file in `Blobstorage & Container.md` file.

2020-12-11 15:50 UTC, gonzalorieto commented
Can we add an example of how it would be if there are more than one birthday. Don't change the one you did, just add an example for more than one birthday.
Other than that, LGTM.

2020-12-11 15:58 UTC, nelsonsouthworks commented
@gonzalorieto your point of view is good, I think that this file could be created with 2 birthdays already as a base. So that the user knows, how it has to go I add a birthday to the file. Thanks

2020-12-15 15:09 UTC, angelszymczak approved these changes

2020-12-15 15:21 UTC, dfavretto requested changes

2020-12-15 15:21 UTC, dfavretto commented on docs/Blobstorage&Container.md
>       1. We **select** the file that we downloaded in step 1.
This line should be modified too, as it's referencing the file downloaded, but we aren't downloading anything anymore.

2020-12-15 19:07 UTC, dfavretto approved these changes

2020-12-15 19:10 UTC, merged