Add YAML file used in publish pipeline in dev environment
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #56
Opened 2020-12-28 18:50 UTC by nelsonsouthworks

Add the yml file of the publish pipeline in the dev environment. Also, add a script to publish

The following variables were retrieved from the Azure KeyVault resource:

- AzureDevOps-BambooHRUsersFileName
- AzureDevOps-BlobStorageConversationContainer
- AzureDevOps-BlobStorageDataUsersContainer
- AzureDevOps-BlobStorageStringConnection
- AzureDevOps-DummyToken
- AzureDevOps-EnabledNotifications
- AzureDevOps-EventHubConnectionString
- AzureDevOps-EventHubName
- AzureDevOps-QueueName
- AzureDevOps-QueueStorageStringConnection
- AzureDevOps-ServicePrincipal-Secret
- AzureDevOps-ServicePrincipal-Tenant
- AzureDevOps-ServicePrincipal-Username
- AzureDevOps-SlackBotToken
- AzureDevOps-SlackClientSigningSecret
- AzureDevOps-SlackVerificationToken
- AzureDevOps-SpecificChannelName
- BirthdayBotName
- BirthdayBotResourceGroup

2020-12-28 19:18 UTC, dfavretto requested changes

2020-12-28 19:18 UTC, dfavretto commented on birthday-bot/appsettings.json
> +  "DummyToken": ""
Why are you adding a `DummyToken` in this PR? What's this used for? It doesn't seem to be necessary.

2020-12-28 19:18 UTC, dfavretto commented on birthday-bot/Pipeline/Azure-Birthday-Bot-Build.yml
> +    value: $(AzureDevops-DummyToken)
Is it correct to use this `DummyToken` here?

2020-12-28 19:37 UTC, nelsonsouthworks commented on birthday-bot/appsettings.json
> +  "DummyToken": ""
No, it was only a test parameter. I'm going to remove it. Thanks

2020-12-28 19:37 UTC, nelsonsouthworks commented on birthday-bot/Pipeline/Azure-Birthday-Bot-Build.yml
> +    value: $(AzureDevops-DummyToken)
No is correct, it was only a test parameter. I'm going to remove it. Thank you

2020-12-30 18:42 UTC, dfavretto requested changes
Left some questions and comments

2020-12-30 18:42 UTC, dfavretto commented on birthday-bot/Pipeline/Azure-Birthday-Bot-Build.yml
> +#Trigger Test
Why is it `Trigger Test`? What are you testing?

2020-12-30 18:42 UTC, dfavretto commented on birthday-bot/Pipeline/Azure-Birthday-Bot-Build.yml
> +    value: $(AzureDevops-EventHubName)
Why are we having Event Hub variables here? Didn't we remove all Event Hub related configuration and logic?

2020-12-30 20:28 UTC, nelsonsouthworks commented on birthday-bot/Pipeline/Azure-Birthday-Bot-Build.yml
> +    value: $(AzureDevops-EventHubName)
They are parameters that follow the appsettings.json and based on that I declare them. They do not have any key because these services do not exist. I already removed it. Thanks

2020-12-30 20:28 UTC, dfavretto approved these changes

2020-12-30 20:28 UTC, merged