Create new function to invoke the BOT every-friday endpoint
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #67
Opened 2023-04-13 17:56 UTC by cristian-uehara

## Description
On this PR we added a new timer trigger function to invoke the every-friday bot endpoint (weekly)

## Specific Changes
  - Added a new setting 'WeeklyProactiveMessageSchedule' to configure the trigger
  - Renamed the 'ProactiveMessageSchedule' setting to 'DailyProactiveMessageSchedule'
  - Added new timer trigger function to invoke the every-friday endpoint

2023-04-13 19:53 UTC, JuanAr requested changes
I added some change request

2023-04-13 19:53 UTC, JuanAr commented on MessagePublisher/DailyProactiveMessageFunction.cs
> +            var botEndpoint = Environment.GetEnvironmentVariable("BotNotifyEndpoint", EnvironmentVariableTarget.Process);
I think I prefer to have two separate app settings, with the complete url because this might get confusing.
Also, validate it has some value and do not GET if empty and log some warning.

2023-04-13 20:54 UTC, erquirogasw submitted a review, later dismissed

2023-04-13 22:47 UTC, cristian-uehara commented on MessagePublisher/DailyProactiveMessageFunction.cs
> +            var botEndpoint = Environment.GetEnvironmentVariable("BotNotifyEndpoint", EnvironmentVariableTarget.Process);
Applied, thanks.

2023-04-14 13:58 UTC, JuanAr approved these changes
LGTM

2023-04-14 16:16 UTC, merged