Remove year from date of birth field
southworks/azure-botsdk-happybirthday-bamboohr-slack-bot pull request #74
Opened 2023-04-19 20:48 UTC by erquirogasw

## Description
This PR removes the _DateOfBirth_ field and replaces it with 2 new fields (_DayOfBirth_ and _MonthOfBirth_) in order to not use the year and follow good data privacy practices.
Additionally, it adds and set in false the _RunOnStartup_ parameter to the function's _Run_ method to make it easier to set the function to run locally.

## Specific Changes
  - Removed _Birthday_ property from the _employeeJson_ object.
  - Added _DayOfBirth_ property from the _employeeJson_ object.
  - Added _MonthOfBirth_ property from the _employeeJson_ object.
  - Added _RunOnStartup_ parameter to the function's _Run_ method.

The following image shows the code changes and the data result.
![image](https://user-images.githubusercontent.com/64815358/233196443-8815567c-bded-45ce-abf6-3bbbc2085b17.png)

2023-04-19 20:57 UTC, JuanAr requested changes
Split in two PRs one per each topic

2023-04-19 20:57 UTC, JuanAr commented on azure-functions/DataIngestionBambooAPI/DataIngestionBambooAPI.cs
> +        public static async Task Run([TimerTrigger("0 0 9 * * *", RunOnStartup = false)] TimerInfo myTimer, ILogger log, ExecutionContext context)
This one goes to another PR

2023-04-20 13:36 UTC, erquirogasw commented on azure-functions/DataIngestionBambooAPI/DataIngestionBambooAPI.cs
> +        public static async Task Run([TimerTrigger("0 0 9 * * *", RunOnStartup = false)] TimerInfo myTimer, ILogger log, ExecutionContext context)
Done. Thanks!

2023-04-20 14:02 UTC, cristian-uehara approved these changes
lgtm!

2023-04-20 19:41 UTC, cristian-uehara approved these changes
lgtm

2023-04-20 20:52 UTC, JuanAr approved these changes
LGTM

2023-04-20 20:54 UTC, merged